version: '3'
services:
  laravel:
    build: ./laravel-app
    ports:
      - "8000:8000"
  golang-api:
    build: ./golang-api
    ports:
      - "8080:8080"
  python-worker:
    build: ./python-scripts
    command: python analyze_forensic_data.py
